# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935e82120117565d31a948f58cb79128cf021d444a47a3050a4d33939a313ab2948ae88a5f2f950b8cdd2fc32d8d5b6b89458164ab469ac5fcdeba9564dd93f2

test:
  secret_key_base: 388553b3a4cbaa0e0563f703557c7111116cc2d4858da9b0b324e719271b721bb16e482e45619e20f230b3a732db65f5e2d95c40956f9c456b07885988ee1a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
